-- INSERT INTO author (first_name, last_name) VALUES ('George R.R', 'Martin');
-- INSERT INTO author (first_name, last_name) VALUES ('John R.R', 'Tolkien');
-- INSERT INTO author (first_name, last_name) VALUES ('Joanne K', 'Rowling');
-- INSERT INTO author (first_name, last_name) VALUES ('C.S', 'Lewis');
--
-- INSERT INTO book (title, author_id, release_date)
-- VALUES ('A Clash of Kings', 1, '1999-05-28 18:06:32');
--
-- INSERT INTO book (title, author_id, release_date)
-- VALUES ('A Dance with Dragons', 1, '2011-05-28 18:06:32');
--
-- INSERT INTO book (title, author_id, release_date)
-- VALUES ('The Fellowship of the Ring', 2, '1954-05-28 18:06:32');
--
-- INSERT INTO book (title, author_id, release_date)
-- VALUES ('Harry Potter and the Philosopher’s Stone', 3, '2000-05-28 18:06:32');
--
-- INSERT INTO book (title, author_id, release_date)
-- VALUES ('The Lion, the Witch and the Wardrobe', 4, '1950-05-28 18:06:32');
